### ISSUE TITLE
README in the repository not consistent with the original sample README provided

### ISSUE THREAD

**Issue by PriyadarshiniRajagopal** [SoftwareEngineeringToolDemos/ICSE-2012-RESOLVE#14]
Th example-repo shows that the readme should have some links to the original project in the format shown below:

Here are some links to the original project:
- The Official Project Page, including source code
- The Tool on the Visual Studio Gallery
- A Video of the Tool

Thanking authors and including student github profiles is done after this. Order of flow not carefully followed.

This repo does not follow this format.

**Comment by kairav** [comment]
Modified as per the original
